using MarketPricingEngine.Application.Abstractions.Repositories;
using MarketPricingEngine.Application.Abstractions.Services;
using MarketPricingEngine.Domain.Entities;
using MarketPricingEngine.Domain.Enums;

namespace MarketPricingEngine.Infrastructure.Services
{
    public class AutoTradingService : IAutoTradingService
    {
        private const decimal AdjustmentPercent = 0.0003m;

        private readonly IOrderRepository orderRepository;
        private readonly ITradingRulesRepository tradingRulesRepository;
        private readonly ITradingRulesEvaluator tradingRulesEvaluator;

        public AutoTradingService(
            IOrderRepository orderRepository,
            ITradingRulesRepository tradingRulesRepository,
            ITradingRulesEvaluator tradingRulesEvaluator)
        {
            this.orderRepository = orderRepository;
            this.tradingRulesRepository = tradingRulesRepository;
            this.tradingRulesEvaluator = tradingRulesEvaluator;
        }

        public async Task EvaluateAsync(PriceTickEntity latestTick, LatestPriceEntity? previousPrice)
        {
            if (previousPrice == null)
            {
                return;
            }

            var rules = await this.tradingRulesRepository.GetAsync();

            if(rules == null)
            {
                return;
            }

            if(latestTick.SpreadPercent <= rules.AutoTradingSpreadThresholdPercent)
            {
                return;
            }

            var currentMid = latestTick.CurrentMarketPrice;
            var previousMid = previousPrice.CurrentMarketPrice;

            if (currentMid == previousMid)
            {
                return;
            }

            OrderSide side;
            decimal price;

            if (currentMid > previousMid)
            {
                side = OrderSide.Sell;
                price = latestTick.AskPrice - (latestTick.AskPrice * AdjustmentPercent);
            }
            else
            {
                side = OrderSide.Buy;
                price = latestTick.BidPrice + (latestTick.BidPrice * AdjustmentPercent);
            }

            var quantity = 1;
            var notional = price * quantity;

            var order = new OrderEntity
            {
                ExternalOrderId = Guid.NewGuid().ToString(),
                Symbol = latestTick.Symbol,
                Side = side,
                Type = OrderType.Limit,
                RequestedPrice = price,
                Quantity = quantity,
                NotionalAmount = notional,
                Source = OrderSource.AutoGenerated,
                CreatedAt = DateTime.UtcNow
            };

            var tradingDecision = await this.tradingRulesEvaluator.EvaluateAsync(order);

            if(tradingDecision.IsAccepted)
            {
                order.Status = OrderStatus.Accepted;
            }
            else
            {
                order.Status = OrderStatus.Rejected;
                order.RejectionReason = string.Join("; ", tradingDecision.RejectedReasons);
            }

            await this.orderRepository.AddAsync(order);
        }
    }
}