// <auto-generated />
using System;
using MarketPricingEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPricingEngine.Infrastructure.Migrations
{
    [DbContext(typeof(MarketPricingDbContext))]
    partial class MarketPricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MarketPricingEngine.Domain.Entities.LatestPriceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("AskPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("ask_price");

                    b.Property<decimal>("BidPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("bid_price");

                    b.Property<decimal>("CurrentMarketPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("current_market_price");

                    b.Property<decimal>("Spread")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("spread");

                    b.Property<decimal>("SpreadPercent")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("spread_percent");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("latest_prices", (string)null);
                });

            modelBuilder.Entity("MarketPricingEngine.Domain.Entities.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_order_id");

                    b.Property<decimal>("NotionalAmount")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("notional_amount");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("rejection_reason");

                    b.Property<decimal>("RequestedPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("requested_price");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("side");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ExternalOrderId");

                    b.HasIndex("Symbol");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("MarketPricingEngine.Domain.Entities.PriceTickEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("AskPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("ask_price");

                    b.Property<decimal>("BidPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("bid_price");

                    b.Property<decimal>("CurrentMarketPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("mid_price");

                    b.Property<decimal>("Spread")
                        .HasColumnType("TEXT")
                        .HasColumnName("spread");

                    b.Property<decimal>("SpreadPercent")
                        .HasColumnType("TEXT")
                        .HasColumnName("spread_percent");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("price_ticks", (string)null);
                });

            modelBuilder.Entity("MarketPricingEngine.Domain.Entities.TradingRulesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AllowedSymbolsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_symbols_csv");

                    b.Property<decimal>("AutoTradingSpreadThresholdPercent")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("auto_trading_spread_threshold_percent");

                    b.Property<bool>("EnableSymbolWhitelist")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable_symbol_whitelist");

                    b.Property<decimal>("MaxNotionalAmount")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("max_notional_amount");

                    b.Property<decimal>("MaxPriceDeviationPercent")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("max_price_deviation_percent");

                    b.Property<long>("MaxQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_quantity");

                    b.Property<bool>("RejectDuplicateOrderIds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reject_duplicate_order_ids");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("trading_rules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
